# Generated by Django 3.1.3 on 2020-11-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('banned_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=45)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('blog_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_id', models.CharField(max_length=45)),
                ('log_no', models.CharField(max_length=45)),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='RatioType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaRatio',
            fields=[
                ('multimedia_ratio_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratio', models.FloatField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bloginfo')),
                ('ratio_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.ratiotype')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=45)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bloginfo')),
                ('feedback_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.feedbacktype')),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('dictionary_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bloginfo')),
                ('dictionary_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.dictionarytype')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzedInfo',
            fields=[
                ('analyzed_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('lorem_percentage', models.FloatField(default=-1)),
                ('tag_similarity', models.FloatField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bloginfo')),
            ],
        ),
    ]
