# Generated by Django 3.1.3 on 2020-11-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedinfo',
            name='sample1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyzedinfo',
            name='sample2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyzedinfo',
            name='sample3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
