# Generated by Django 3.1.3 on 2020-11-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201108_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedinfo',
            name='lorem_percentage',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='analyzedinfo',
            name='tag_similarity',
            field=models.FloatField(default=-1),
        ),
    ]
