# Generated by Django 3.1.3 on 2020-11-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201108_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediaratio',
            name='ratio',
            field=models.FloatField(default=-1),
        ),
    ]
